version: "3.7"
services:
  db:
    image: mongo:3.6.1
    container_name: mongo
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.s/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
volumes:
  mongodb: